Galactic Empire Ship Configuration Table
Version ge-arena 0.3

LEVEL4 {}

Type of ship class 01:
USER for player-controlled ships.
CYBORG for Cybertrons.
DROID for all other NPC ships.

S01TYPE {Class 01 type of ship: USER} E USER CYBORG DROID <NONE>

Name of class of ship for class 01.

S01NAME {Interceptor} (S01TYPE#<NONE>) S 29 Class 01 name

Name of ship of class 01 (NPCs only).
This will be appended with a numerical identifier.

S01SNAME {} (S01TYPE=CYBORG,DROID) S 29 Ship 01 name

Maximum shield type for class 01. 0 for no shields at all.
For arena users, the starting shield type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S01SHLD {Maximum shield type: 8} (S01TYPE#<NONE>) N 0 19

Maximum phaser type for class 01. 0 for no phasers at all.
For arena users, the starting phaser type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S01PHSR {Maximum phaser type: 8} (S01TYPE#<NONE>) N 0 19

Number of torpedo launchers for class 01.

S01TORP {Number of torpedo launchers: 1} (S01TYPE#<NONE>) N 0 3

Number of missile launchers for class 01.

S01MISL {Number of missile launchers: 0} (S01TYPE#<NONE>) N 0 3

Decoy capability for class 01.

S01DECY {Has decoy capability? YES} (S01TYPE#<NONE>) B

Jammer capability for class 01.

S01JAMMR {Has jammer capability? YES} (S01TYPE#<NONE>) B

Zipper capability for class 01.

S01ZIPPR {Has zipper capability? NO} (S01TYPE#<NONE>) B

Mine capability for class 01.

S01MINE {Has mine capability? NO} (S01TYPE#<NONE>) B

Starting phaser type for class 01.
This cannot exceed the maximum phaser type.

S01SPHS {Starting phaser type: 5} (S01TYPE=USER,CYBORG) N 0 19

Starting shield type for class 01.
This cannot exceed the maximum shield type.

S01SSHD {Starting shield type: 5} (S01TYPE=USER,CYBORG) N 0 19

Acceleration rate of class 01.
1000 means one warp speed increment per ship tick.
Immobile NPCs (e.g. Cyber-Base) should have this set to 0,
which will exclude them from all routines that involve
pursuing other ships.

S01ACCL {Acceleration rate: 5000} (S01TYPE#<NONE>) N 0 32767

Maximum warp cruising speed of class 01.
For user ships, actual top speed is 1.5x this value, but
causes engine damage over time. A value of 0 means impulse
only. To make a class completely immobile, set SXXACCL to 0
as well.

S01WARP {Maximum warp cruising speed: 10} (S01TYPE#<NONE>) N 0 255

Maximum cargo capacity of class 01 in tons.

S01TONS {Maximum tonnage: 5000} (S01TYPE#<NONE>) L 1 2000000000

Starting torpedoes for class 01.

S01STOR {Starting torpedoes: 10} (S01TYPE=USER,CYBORG) N 0 255

Starting missiles for class 01.

S01SMIS {Starting missiles: 0} (S01TYPE=USER,CYBORG) N 0 255

Starting mines for class 01.

S01SMIN {Starting mines: 0} (S01TYPE=USER,CYBORG) N 0 255

Starting flux pods for class 01.

S01SFLX {Starting flux pods: 3} (S01TYPE=USER,CYBORG) N 0 255

Starting zippers for class 01.

S01SZIP {Starting zippers: 0} (S01TYPE=USER,CYBORG) N 0 255

Starting jammers for class 01.

S01SJAM {Starting jammers: 1} (S01TYPE=USER,CYBORG) N 0 255

Starting decoys for class 01.

S01SDEC {Starting decoys: 2} (S01TYPE=USER,CYBORG) N 0 255

Starting gold for class 01.

S01SGOL {Starting gold: 0} (S01TYPE=USER,CYBORG) N 0 255

Points awarded for destroying a class 01 ship.

S01PNTS {Points awarded: 750} (S01TYPE#<NONE>) N 1 32767

Scanner range of a class 01 ship in subsectors.

S01SRNG {Scanner range: 100000} (S01TYPE#<NONE>) L 1 10000000

Will Cybertrons fire on a class 01 ship unprovoked?
If YES, Cybertrons will pursue and fire upon this class.
If NO:
For USER ships, Cybertrons will pursue this class but not
fire on unprovoked.
For DROID ships, Cybertrons will ignore this class.

S01CATK {Cybs will fire on this ship: NO} (S01TYPE=USER,DROID) B

How many Cybertrons will pursue a class 01 ship?
Cybertrons will only pursue DROID ships if SXXCATK is YES.

S01NATK {Number of Cybs to pursue this ship: 1} (S01TYPE=USER,DROID) N 0 5

Lowest class of user ship a class 01 NPC will pursue?

S01LATK {Lowest class of user ship this ship will pursue: 0} (S01TYPE=CYBORG,DROID) N 0 50

How many class 01 ships should be created (NPCs only)?

S01MAKE {Number of NPCs of this class to make: 0} (S01TYPE=CYBORG,DROID) N 0 255

Toughness level of class 01 (NPCs only)?
This is a level from 0 to 4.

S01TOUGH {Toughness level: 0} (S01TYPE=CYBORG,DROID) N 0 4

Class 01 damage factor, 100 is normal. 200 is twice as
resilient. 77 is the minimum.
Damage = damage / (SnnDAMF / 100)

S01DAMF {Damage effect factor: 100} (S01TYPE#<NONE>) N 77 32767

Class 01 faction code.
0 for user ships. 1 for Cybertrons.
2 for Sartens. 3 for Lydorians. 4 for Murdonians.
5 for Vakories. 6 for Tryklons. 7 for Zygorians.
NPCs with the same code will not attack each other or
register "friendly fire" on each other with phasers.

S01FCTN {Faction code: 0} (S01TYPE#<NONE>) N 0 255

Class 01 loadout/upgrade code. 0 for Cybertrons.
1 for Lydorian Garbage Scow. 2 for Murdonian Transport.
3 for Vakory Survey Drone. 4 for Sarten Civil Transport.
5 for Sarten Attack Drone. 6 for Galactic Command Freighter.
For user ships, set to the byte value of available
upgrades.

S01LOUT {Loadout code: 24} (S01TYPE=USER,DROID) N 0 255

Arena game mode that uses class 01.

S01MODE {Arena game mode: 1} (S01TYPE#<NONE>) N 1 255

This is the in-game help that is displayed for class 01.
Press F2 to edit.

S01HELP {
[1;36mDetailed Class Specification
[0;31m-----------------------------------------------------------------------------
[1;37mShip class: [1;32mInterceptor   [1;37mLength: [1;32m156m    [1;37mWidth: [1;32m52m   [1;37mHeight: [1;32m17m
[1;37mShields: [1;32mMark-8 maximum   [1;37mPhasers: [1;32mMark-8 maximum   [1;37mTorpedo launchers: [1;32m1
[1;37mMissile launchers: [0;31m0   [1;37mDecoy launcher: [1;32mYes   [1;37mJammer launcher: [1;32mYes
[1;37mZipper launcher: [0;31mNo   [1;37mMine launcher: [0;31mNo
[1;37mAcceleration rate: [1;32m5,000 Su/T   [1;37mTop rated speed: [1;32mWarp 10
[1;37mScanner range: [1;32m100,000 subsectors (10 sectors)   [1;37mCargo capacity: [1;32m5,000 Tons

[1;37mBattle loadout:

Mark-5 shield, Mark-5 phaser, 10 torpedoes, 2 decoys, 1 jammer, 3 flux pods

Eligible upgrades:

none

} (S01TYPE=USER) T   Help screen for class 01

Type of ship class 02:
USER for player-controlled ships.
CYBORG for Cybertrons.
DROID for all other NPC ships.

S02TYPE {Class 02 type of ship: USER} E USER CYBORG DROID <NONE> 

Name of class of ship for class 02.

S02NAME {Minelayer} (S02TYPE#<NONE>) S 29 Class 02 name

Name of ship of class 02 (NPCs only).
This will be appended with a numerical identifier.

S02SNAME {} (S02TYPE=CYBORG,DROID) S 29 Ship 02 name

Maximum shield type for class 02. 0 for no shields at all.
For arena users, the starting shield type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S02SHLD {Maximum shield type: 10} (S02TYPE#<NONE>) N 0 19

Maximum phaser type for class 02. 0 for no phasers at all.
For arena users, the starting phaser type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S02PHSR {Maximum phaser type: 3} (S02TYPE#<NONE>) N 0 19

Number of torpedo launchers for class 02.

S02TORP {Number of torpedo launchers: 0} (S02TYPE#<NONE>) N 0 3

Number of missile launchers for class 02.

S02MISL {Number of missile launchers: 0} (S02TYPE#<NONE>) N 0 3

Decoy capability for class 02.

S02DECY {Has decoy capability? NO} (S02TYPE#<NONE>) B

Jammer capability for class 02.

S02JAMMR {Has jammer capability? NO} (S02TYPE#<NONE>) B

Zipper capability for class 02.

S02ZIPPR {Has zipper capability? YES} (S02TYPE#<NONE>) B

Mine capability for class 02.

S02MINE {Has mine capability? YES} (S02TYPE#<NONE>) B

Starting phaser type for class 02.
This cannot exceed the maximum phaser type.

S02SPHS {Starting phaser type: 1} (S02TYPE=USER,CYBORG) N 0 19

Starting shield type for class 02.
This cannot exceed the maximum shield type.

S02SSHD {Starting shield type: 4} (S02TYPE=USER,CYBORG) N 0 19

Acceleration rate of class 02.
1000 means one warp speed increment per ship tick.
Immobile NPCs (e.g. Cyber-Base) should have this set to 0,
which will exclude them from all routines that involve
pursuing other ships.

S02ACCL {Acceleration rate: 5000} (S02TYPE#<NONE>) N 0 32767

Maximum warp cruising speed of class 02.
For user ships, actual top speed is 1.5x this value, but
causes engine damage over time. A value of 0 means impulse
only. To make a class completely immobile, set SXXACCL to 0
as well.

S02WARP {Maximum warp cruising speed: 15} (S02TYPE#<NONE>) N 0 255

Maximum cargo capacity of class 02 in tons.

S02TONS {Maximum tonnage: 30000} (S02TYPE#<NONE>) L 1 2000000000

Starting torpedoes for class 02.

S02STOR {Starting torpedoes: 0} (S02TYPE=USER,CYBORG) N 0 255

Starting missiles for class 02.

S02SMIS {Starting missiles: 0} (S02TYPE=USER,CYBORG) N 0 255

Starting mines for class 02.

S02SMIN {Starting mines: 20} (S02TYPE=USER,CYBORG) N 0 255

Starting flux pods for class 02.

S02SFLX {Starting flux pods: 3} (S02TYPE=USER,CYBORG) N 0 255

Starting zippers for class 02.

S02SZIP {Starting zippers: 2} (S02TYPE=USER,CYBORG) N 0 255

Starting jammers for class 02.

S02SJAM {Starting jammers: 0} (S02TYPE=USER,CYBORG) N 0 255

Starting decoys for class 02.

S02SDEC {Starting decoys: 0} (S02TYPE=USER,CYBORG) N 0 255

Starting gold for class 02.

S02SGOL {Starting gold: 0} (S02TYPE=USER,CYBORG) N 0 255

Points awarded for destroying a class 02 ship.

S02PNTS {Points awarded: 1500} (S02TYPE#<NONE>) N 1 32767

Scanner range of a class 02 ship in subsectors.

S02SRNG {Scanner range: 100000} (S02TYPE#<NONE>) L 1 10000000

Will Cybertrons fire on a class 02 ship unprovoked?
If YES, Cybertrons will pursue and fire upon this class.
If NO:
For USER ships, Cybertrons will pursue this class but not
fire on unprovoked.
For DROID ships, Cybertrons will ignore this class.

S02CATK {Cybs will fire on this ship: YES} (S02TYPE=USER,DROID) B

How many Cybertrons will pursue a class 02 ship?
Cybertrons will only pursue DROID ships if SXXCATK is YES.

S02NATK {Number of Cybs to pursue this ship: 2} (S02TYPE=USER,DROID) N 0 5

Lowest class of user ship a class 02 Cybertron will pursue?

S02LATK {Lowest class of user ship this ship will pursue: 0} (S02TYPE=CYBORG,DROID) N 0 50

How many class 02 ships should be created (NPCs only)? 

S02MAKE {Number of NPCs of this class to make: 0} (S02TYPE=CYBORG,DROID) N 0 255

Toughness level of class 02 (NPCs only)?
This is a level from 0 to 4.

S02TOUGH {Toughness level: 0} (S02TYPE=CYBORG,DROID) N 0 4

Class 02 damage factor, 100 is normal. 200 is twice as
resilient, 77 is the minimum.
Damage = damage / (SnnDAMF / 100)

S02DAMF {Damage effect factor: 125} (S02TYPE#<NONE>) N 77 32767

Class 02 faction code.
0 for user ships. 1 for Cybertrons.
2 for Sartens. 3 for Lydorians. 4 for Murdonians.
5 for Vakories. 6 for Tryklons. 7 for Zygorians.
NPCs with the same code will not attack each other or
register "friendly fire" on each other with phasers.

S02FCTN {Faction code: 0} (S02TYPE#<NONE>) N 0 255

Class 02 loadout/upgrade code. 0 for Cybertrons.
1 for Lydorian Garbage Scow. 2 for Murdonian Transport.
3 for Vakory Survey Drone. 4 for Sarten Civil Transport.
5 for Sarten Attack Drone. 6 for Galactic Command Freighter.
For user ships, set to the byte value of available
upgrades.

S02LOUT {Loadout code: 34} (S02TYPE=USER,DROID) N 0 255

Arena game mode that uses class 02.

S02MODE {Arena game mode: 1} (S02TYPE#<NONE>) N 1 255

This is the in-game help that is displayed for class 02.
Press F2 to edit.

S02HELP {
[1;36mDetailed Class Specification
[0;31m-----------------------------------------------------------------------------
[1;37mShip class: [1;32mMinelayer  [1;37mLength: [1;32m937m    [1;37mWidth: [1;32m312m   [1;37mHeight: [1;32m96m
[1;37mShields: [1;32mMark-10 maximum   [1;37mPhasers: [1;32mMark-3 maximum   [1;37mTorpedo launchers: [0;31m0
[1;37mMissile launchers: [0;31m0   [1;37mDecoy launcher: [0;31mNo   [1;37mJammer launcher: [0;31mNo
[1;37mZipper launcher: [1;32mYes   [1;37mMine launcher: [1;32mYes
[1;37mAcceleration rate: [1;32m5,000 Su/T   [1;37mTop rated speed: [1;32mWarp 15
[1;37mScanner range: [1;32m100,000 subsectors (10 sectors)   [1;37mCargo capacity: [1;32m30,000 Tons

[1;37mBattle loadout:

Mark-4 shield, Mark-1 phaser, 20 mines, 2 zippers, 3 flux pods

Eligible upgrades:

Armor plating

} (S02TYPE=USER) T   Help screen for class 02

Type of ship class 03:
USER for player-controlled ships.
CYBORG for Cybertrons.
DROID for all other NPC ships.

S03TYPE {Class 03 type of ship: USER} E USER CYBORG DROID <NONE>  

Name of class of ship for class 03.

S03NAME {Monitor} (S03TYPE#<NONE>) S 29 Class 03 name

Name of ship of class 03 (NPCs only).
This will be appended with a numerical identifier.

S03SNAME {} (S03TYPE=CYBORG,DROID) S 29 Ship 03 name

Maximum shield type for class 03. 0 for no shields at all.
For arena users, the starting shield type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S03SHLD {Maximum shield type: 5} (S03TYPE#<NONE>) N 0 19

Maximum phaser type for class 03. 0 for no phasers at all.
For arena users, the starting phaser type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S03PHSR {Maximum phaser type: 15} (S03TYPE#<NONE>) N 0 19

Number of torpedo launchers for class 03.

S03TORP {Number of torpedo launchers: 2} (S03TYPE#<NONE>) N 0 3

Number of missile launchers for class 03.

S03MISL {Number of missile launchers: 0} (S03TYPE#<NONE>) N 0 3

Decoy capability for class 03.

S03DECY {Has decoy capability? YES} (S03TYPE#<NONE>) B

Jammer capability for class 03.

S03JAMMR {Has jammer capability? YES} (S03TYPE#<NONE>) B

Zipper capability for class 03.

S03ZIPPR {Has zipper capability? YES} (S03TYPE#<NONE>) B

Mine capability for class 03.

S03MINE {Has mine capability? NO} (S03TYPE#<NONE>) B

Starting phaser type for class 03.
This cannot exceed the maximum phaser type.

S03SPHS {Starting phaser type: 4} (S03TYPE=USER,CYBORG) N 0 19

Starting shield type for class 03.
This cannot exceed the maximum shield type.

S03SSHD {Starting shield type: 2} (S03TYPE=USER,CYBORG) N 0 19

Acceleration rate of class 03.
1000 means one warp speed increment per ship tick.
Immobile NPCs (e.g. Cyber-Base) should have this set to 0,
which will exclude them from all routines that involve
pursuing other ships.

S03ACCL {Acceleration rate: 8000} (S03TYPE#<NONE>) N 0 32767

Maximum warp cruising speed of class 03.
For user ships, actual top speed is 1.5x this value, but
causes engine damage over time. A value of 0 means impulse
only. To make a class completely immobile, set SXXACCL to 0
as well.

S03WARP {Maximum warp cruising speed: 20} (S03TYPE#<NONE>) N 0 255

Maximum cargo capacity of class 03 in tons.

S03TONS {Maximum tonnage: 20000} (S03TYPE#<NONE>) L 1 2000000000

Starting torpedoes for class 03.

S03STOR {Starting torpedoes: 5} (S03TYPE=USER,CYBORG) N 0 255

Starting missiles for class 03.

S03SMIS {Starting missiles: 0} (S03TYPE=USER,CYBORG) N 0 255

Starting mines for class 03.

S03SMIN {Starting mines: 0} (S03TYPE=USER,CYBORG) N 0 255

Starting flux pods for class 03.

S03SFLX {Starting flux pods: 3} (S03TYPE=USER,CYBORG) N 0 255

Starting zippers for class 03.

S03SZIP {Starting zippers: 1} (S03TYPE=USER,CYBORG) N 0 255

Starting jammers for class 03.

S03SJAM {Starting jammers: 0} (S03TYPE=USER,CYBORG) N 0 255

Starting decoys for class 03.

S03SDEC {Starting decoys: 2} (S03TYPE=USER,CYBORG) N 0 255

Starting gold for class 03.

S03SGOL {Starting gold: 0} (S03TYPE=USER,CYBORG) N 0 255

Points awarded for destroying a class 03 ship.

S03PNTS {Points awarded: 1000} (S03TYPE#<NONE>) N 1 32767

Scanner range of a class 03 ship in subsectors.

S03SRNG {Scanner range: 200000} (S03TYPE#<NONE>) L 1 10000000

Will Cybertrons fire on a class 03 ship unprovoked?
If YES, Cybertrons will pursue and fire upon this class.
If NO:
For USER ships, Cybertrons will pursue this class but not
fire on unprovoked.
For DROID ships, Cybertrons will ignore this class.

S03CATK {Cybs will fire on this ship: YES} (S03TYPE=USER,DROID) B

How many Cybertrons will pursue a class 03 ship?
Cybertrons will only pursue DROID ships if SXXCATK is YES.

S03NATK {Number of Cybs to pursue this ship: 2} (S03TYPE=USER,DROID) N 0 5

Lowest class of user ship a class 03 Cybertron will pursue?

S03LATK {Lowest class of user ship this ship will pursue: 0} (S03TYPE=CYBORG,DROID) N 0 50

How many class 03 ships should be created (NPCs only)?

S03MAKE {Number of NPCs of this class to make: 0} (S03TYPE=CYBORG,DROID) N 0 255

Toughness level of class 03 (NPCs only)?
This is a level from 0 to 4.

S03TOUGH {Toughness level: 0} (S03TYPE=CYBORG,DROID) N 0 4

Class 03 damage factor, 100 is normal. 200 is twice as
resilient, 77 is the minimum.
Damage = damage / (SnnDAMF / 100)

S03DAMF {Damage effect factor: 130} (S03TYPE#<NONE>) N 77 32767

Class 03 faction code.
0 for user ships. 1 for Cybertrons.
2 for Sartens. 3 for Lydorians. 4 for Murdonians.
5 for Vakories. 6 for Tryklons. 7 for Zygorians.
NPCs with the same code will not attack each other or
register "friendly fire" on each other with phasers.

S03FCTN {Faction code: 0} (S03TYPE#<NONE>) N 0 255

Class 03 loadout/upgrade code. 0 for Cybertrons.
1 for Lydorian Garbage Scow. 2 for Murdonian Transport.
3 for Vakory Survey Drone. 4 for Sarten Civil Transport.
5 for Sarten Attack Drone. 6 for Galactic Command Freighter.
For user ships, set to the byte value of available
upgrades.

S03LOUT {Loadout code: 177} (S03TYPE=USER,DROID) N 0 255

Arena game mode that uses class 03.

S03MODE {Arena game mode: 1} (S03TYPE#<NONE>) N 1 255

This is the in-game help that is displayed for class 03.
Press F2 to edit.

S03HELP {
[1;36mDetailed Class Specification
[0;31m-----------------------------------------------------------------------------
[1;37mShip class: [1;32mMonitor  [1;37mLength: [1;32m625m    [1;37mWidth: [1;32m208m   [1;37mHeight: [1;32m112m
[1;37mShields: [1;32mMark-5 maximum   [1;37mPhasers: [1;32mMark-15 maximum   [1;37mTorpedo launchers: [1;32m2
[1;37mMissile launchers: [0;31m0   [1;37mDecoy launcher: [1;32mYes   [1;37mJammer launcher: [1;32mYes
[1;37mZipper launcher: [1;32mYes   [1;37mMine launcher: [0;31mNo
[1;37mAcceleration rate: [1;32m8,000 Su/T   [1;37mTop rated speed: [1;32mWarp 20
[1;37mScanner range: [1;32m200,000 subsectors (20 sectors)   [1;37mCargo capacity: [1;32m20,000 Tons

[1;37mBattle loadout:

Mark-2 shield, Mark-4 phaser, 5 torpedoes, 2 decoys, 1 zipper, 3 flux pods

Eligible upgrades:

Enhanced scanners, reinforced neutron core

} (S03TYPE=USER) T   Help screen for class 03

Type of ship class 04:
USER for player-controlled ships.
CYBORG for Cybertrons.
DROID for all other NPC ships.

S04TYPE {Class 04 type of ship: USER} E USER CYBORG DROID <NONE> 

Name of class of ship for class 04.

S04NAME {Destroyer} (S04TYPE#<NONE>) S 29 Class 04 name

Name of ship of class 04 (NPCs only).
This will be appended with a numerical identifier.

S04SNAME {} (S04TYPE=CYBORG,DROID) S 29 Ship 04 name

Maximum shield type for class 04. 0 for no shields at all.
For arena users, the starting shield type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S04SHLD {Maximum shield type: 10} (S04TYPE#<NONE>) N 0 19

Maximum phaser type for class 04. 0 for no phasers at all.
For arena users, the starting phaser type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S04PHSR {Maximum phaser type: 10} (S04TYPE#<NONE>) N 0 19

Number of torpedo launchers for class 04.

S04TORP {Number of torpedo launchers: 2} (S04TYPE#<NONE>) N 0 3

Number of missile launchers for class 04.

S04MISL {Number of missile launchers: 1} (S04TYPE#<NONE>) N 0 3

Decoy capability for class 04.

S04DECY {Has decoy capability? YES} (S04TYPE#<NONE>) B

Jammer capability for class 04.

S04JAMMR {Has jammer capability? YES} (S04TYPE#<NONE>) B

Zipper capability for class 04.

S04ZIPPR {Has zipper capability? YES} (S04TYPE#<NONE>) B

Mine capability for class 04.

S04MINE {Has mine capability? YES} (S04TYPE#<NONE>) B

Starting phaser type for class 04.
This cannot exceed the maximum phaser type.

S04SPHS {Starting phaser type: 2} (S04TYPE=USER,CYBORG) N 0 19

Starting shield type for class 04.
This cannot exceed the maximum shield type.

S04SSHD {Starting shield type: 2} (S04TYPE=USER,CYBORG) N 0 19

Acceleration rate of class 04.
1000 means one warp speed increment per ship tick.
Immobile NPCs (e.g. Cyber-Base) should have this set to 0,
which will exclude them from all routines that involve
pursuing other ships.

S04ACCL {Acceleration rate: 10000} (S04TYPE#<NONE>) N 0 32767

Maximum warp cruising speed of class 04.
For user ships, actual top speed is 1.5x this value, but
causes engine damage over time. A value of 0 means impulse
only. To make a class completely immobile, set SXXACCL to 0
as well.

S04WARP {Maximum warp cruising speed: 25} (S04TYPE#<NONE>) N 0 255

Maximum cargo capacity of class 04 in tons.

S04TONS {Maximum tonnage: 20000} (S04TYPE#<NONE>) L 1 2000000000

Starting torpedoes for class 04.

S04STOR {Starting torpedoes: 2} (S04TYPE=USER,CYBORG) N 0 255

Starting missiles for class 04.

S04SMIS {Starting missiles: 2} (S04TYPE=USER,CYBORG) N 0 255

Starting mines for class 04.

S04SMIN {Starting mines: 0} (S04TYPE=USER,CYBORG) N 0 255

Starting flux pods for class 04.

S04SFLX {Starting flux pods: 3} (S04TYPE=USER,CYBORG) N 0 255

Starting zippers for class 04.

S04SZIP {Starting zippers: 0} (S04TYPE=USER,CYBORG) N 0 255

Starting jammers for class 04.

S04SJAM {Starting jammers: 1} (S04TYPE=USER,CYBORG) N 0 255

Starting decoys for class 04.

S04SDEC {Starting decoys: 0} (S04TYPE=USER,CYBORG) N 0 255

Starting gold for class 04.

S04SGOL {Starting gold: 0} (S04TYPE=USER,CYBORG) N 0 255

Points awarded for destroying a class 04 ship.

S04PNTS {Points awarded: 2000} (S04TYPE#<NONE>) N 1 32767

Scanner range of a class 04 ship in subsectors.

S04SRNG {Scan range: 150000} (S04TYPE#<NONE>) L 1 10000000

Will Cybertrons fire on a class 04 ship unprovoked?
If YES, Cybertrons will pursue and fire upon this class.
If NO:
For USER ships, Cybertrons will pursue this class but not
fire on unprovoked.
For DROID ships, Cybertrons will ignore this class.

S04CATK {Cybs will fire on this ship: YES} (S04TYPE=USER,DROID) B

How many Cybertrons will pursue a class 04 ship?
Cybertrons will only pursue DROID ships if SXXCATK is YES.

S04NATK {Number of Cybs to pursue this ship: 2} (S04TYPE=USER,DROID) N 0 5

Lowest class of user ship a class 04 Cybertron will pursue?

S04LATK {Lowest class of user ship this ship will pursue: 0} (S04TYPE=CYBORG,DROID) N 0 50

How many class 04 ships should be created (NPCs only)?

S04MAKE {Number of NPCs of this class to make: 0} (S04TYPE=CYBORG,DROID) N 0 255

Toughness level of class 04 (NPCs only)?
This is a level from 0 to 4.

S04TOUGH {Toughness level: 0} (S04TYPE=CYBORG,DROID) N 0 4

Class 04 damage factor, 100 is normal. 200 is twice as
resilient, 77 is the minimum.
Damage = damage / (SnnDAMF / 100)

S04DAMF {Damage effect factor: 175} (S04TYPE#<NONE>) N 77 32767

Class 04 faction code.
0 for user ships. 1 for Cybertrons.
2 for Sartens. 3 for Lydorians. 4 for Murdonians.
5 for Vakories. 6 for Tryklons. 7 for Zygorians.
NPCs with the same code will not attack each other or
register "friendly fire" on each other with phasers.

S04FCTN {Faction code: 0} (S04TYPE#<NONE>) N 0 255

Class 04 loadout/upgrade code. 0 for Cybertrons.
1 for Lydorian Garbage Scow. 2 for Murdonian Transport.
3 for Vakory Survey Drone. 4 for Sarten Civil Transport.
5 for Sarten Attack Drone. 6 for Galactic Command Freighter.
For user ships, set to the byte value of available
upgrades.

S04LOUT {Loadout code: 251} (S04TYPE=USER,DROID) N 0 255

Arena game mode that uses class 04.

S04MODE {Arena game mode: 1} (S04TYPE#<NONE>) N 1 255

This is the in-game help that is displayed for class 04.
Press F2 to edit.

S04HELP {
[1;36mDetailed Class Specification
[0;31m-----------------------------------------------------------------------------
[1;37mShip class: [1;32mDestroyer  [1;37mLength: [1;32m625m    [1;37mWidth: [1;32m208m   [1;37mHeight: [1;32m124m
[1;37mShields: [1;32mMark-10 maximum   [1;37mPhasers: [1;32mMark-10 maximum   [1;37mTorpedo launchers: [1;32m2
[1;37mMissile launchers: [1;32m1   [1;37mDecoy launcher: [1;32mYes   [1;37mJammer launcher: [1;32mYes
[1;37mZipper launcher: [1;32mYes   [1;37mMine launcher: [1;32mYes
[1;37mAcceleration rate: [1;32m10,000 Su/T   [1;37mTop rated speed: [1;32mWarp 25
[1;37mScanner range: [1;32m150,000 subsectors (15 sectors)   [1;37mCargo capacity: [1;32m20,000 Tons

[1;37mBattle loadout:

Mark-2 shield, Mark-2 phaser, 2 torpedoes, 2 missiles, 1 jammer, 3 flux pods

Eligible upgrades:

Enhanced scanners, armor plating, reinforced neutron core

} (S04TYPE=USER) T   Help screen for class 04

Type of ship class 05:
USER for player-controlled ships.
CYBORG for Cybertrons.
DROID for all other NPC ships.

S05TYPE {Class 05 type of ship: USER} E USER CYBORG DROID <NONE> 

Name of class of ship for class 05.

S05NAME {Battle Cruiser} (S05TYPE#<NONE>) S 29 Class 05 name

Name of ship of class 05 (NPCs only).
This will be appended with a numerical identifier.

S05SNAME {} (S05TYPE=CYBORG,DROID) S 29 Ship 05 name

Maximum shield type for class 05. 0 for no shields at all.
For arena users, the starting shield type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S05SHLD {Maximum shield type: 16} (S05TYPE#<NONE>) N 0 19

Maximum phaser type for class 05. 0 for no phasers at all.
For arena users, the starting phaser type is configured separately.
For NPCs, this will be a random value
between 1 and this class.

S05PHSR {Maximum phaser type: 16} (S05TYPE#<NONE>) N 0 19

Number of torpedo launchers for class 05.

S05TORP {Number of torpedo launchers: 2} (S05TYPE#<NONE>) N 0 3

Number of missile launchers for class 05.

S05MISL {Number of missile launchers: 2} (S05TYPE#<NONE>) N 0 3

Decoy capability for class 05.

S05DECY {Has decoy capability? YES} (S05TYPE#<NONE>) B

Jammer capability for class 05.

S05JAMMR {Has jammer capability? YES} (S05TYPE#<NONE>) B

Zipper capability for class 05.

S05ZIPPR {Has zipper capability? YES} (S05TYPE#<NONE>) B

Mine capability for class 05.

S05MINE {Has mine capability? YES} (S05TYPE#<NONE>) B

Starting phaser type for class 05.
This cannot exceed the maximum phaser type.

S05SPHS {Starting phaser type: 1} (S05TYPE=USER,CYBORG) N 0 19

Starting shield type for class 05.
This cannot exceed the maximum shield type.

S05SSHD {Starting shield type: 1} (S05TYPE=USER,CYBORG) N 0 19

Acceleration rate of class 05.
1000 means one warp speed increment per ship tick.
Immobile NPCs (e.g. Cyber-Base) should have this set to 0,
which will exclude them from all routines that involve
pursuing other ships.

S05ACCL {Acceleration rate: 6000} (S05TYPE#<NONE>) N 0 32767

Maximum warp cruising speed of class 05.
For user ships, actual top speed is 1.5x this value, but
causes engine damage over time. A value of 0 means impulse
only. To make a class completely immobile, set SXXACCL to 0
as well.

S05WARP {Maximum warp cruising speed: 35} (S05TYPE#<NONE>) N 0 255

Maximum cargo capacity of class 05 in tons.

S05TONS {Maximum tonnage: 40000} (S05TYPE#<NONE>) L 1 2000000000

Starting torpedoes for class 05.

S05STOR {Starting torpedoes: 0} (S05TYPE=USER,CYBORG) N 0 255

Starting missiles for class 05.

S05SMIS {Starting missiles: 0} (S05TYPE=USER,CYBORG) N 0 255

Starting mines for class 05.

S05SMIN {Starting mines: 0} (S05TYPE=USER,CYBORG) N 0 255

Starting flux pods for class 05.

S05SFLX {Starting flux pods: 3} (S05TYPE=USER,CYBORG) N 0 255

Starting zippers for class 05.

S05SZIP {Starting zippers: 0} (S05TYPE=USER,CYBORG) N 0 255

Starting jammers for class 05.

S05SJAM {Starting jammers: 0} (S05TYPE=USER,CYBORG) N 0 255

Starting decoys for class 05.

S05SDEC {Starting decoys: 0} (S05TYPE=USER,CYBORG) N 0 255

Starting gold for class 05.

S05SGOL {Starting gold: 0} (S05TYPE=USER,CYBORG) N 0 255

Points awarded for destroying a class 05 ship.

S05PNTS {Points awarded: 5000} (S05TYPE#<NONE>) N 1 32767

Scanner range of a class 05 ship in subsectors.

S05SRNG {Scan range: 250000} (S05TYPE#<NONE>) L 1 10000000

Will Cybertrons fire on a class 05 ship unprovoked?
If YES, Cybertrons will pursue and fire upon this class.
If NO:
For USER ships, Cybertrons will pursue this class but not
fire on unprovoked.
For DROID ships, Cybertrons will ignore this class.

S05CATK {Cybs will fire on this ship: YES} (S05TYPE=USER,DROID) B

How many Cybertrons will pursue a class 05 ship?
Cybertrons will only pursue DROID ships if SXXCATK is YES.

S05NATK {Number of Cybs to pursue this ship: 3} (S05TYPE=USER,DROID) N 0 5

Lowest class of user ship a class 05 Cybertron will pursue?

S05LATK {Lowest class of user ship this ship will pursue: 0} (S05TYPE=CYBORG,DROID) N 0 50

How many class 05 ships should be created (NPCs only)?

S05MAKE {Number of NPCs of this class to make: 0} (S05TYPE=CYBORG,DROID) N 0 255

Toughness level of class 05 (NPCs only)?
This is a level from 0 to 4.

S05TOUGH {Toughness level: 0} (S05TYPE=CYBORG,DROID) N 0 4

Class 05 damage factor, 100 is normal. 200 is twice as
resilient, 77 is the minimum.
Damage = damage / (SnnDAMF / 100)

S05DAMF {Damage effect factor: 225} (S05TYPE#<NONE>) N 77 32767

Class 05 faction code.
0 for user ships. 1 for Cybertrons.
2 for Sartens. 3 for Lydorians. 4 for Murdonians.
5 for Vakories. 6 for Tryklons. 7 for Zygorians.
NPCs with the same code will not attack each other or
register "friendly fire" on each other with phasers.

S05FCTN {Faction code: 0} (S05TYPE#<NONE>) N 0 255

Class 05 loadout/upgrade code. 0 for Cybertrons.
1 for Lydorian Garbage Scow. 2 for Murdonian Transport.
3 for Vakory Survey Drone. 4 for Sarten Civil Transport.
5 for Sarten Attack Drone. 6 for Galactic Command Freighter.
For user ships, set to the byte value of available
upgrades.

S05LOUT {Loadout code: 255} (S05TYPE=USER,DROID) N 0 255

Arena game mode that uses class 05.

S05MODE {Arena game mode: 1} (S05TYPE#<NONE>) N 1 255

This is the in-game help that is displayed for class 05.
Press F2 to edit.

S05HELP {
[1;36mDetailed Class Specification
[0;31m-----------------------------------------------------------------------------
[1;37mShip class: [1;32mBattle Cruiser  [1;37mLength: [1;32m937m    [1;37mWidth: [1;32m312m   [1;37mHeight: [1;32m204m
[1;37mShields: [1;32mMark-16 maximum   [1;37mPhasers: [1;32mMark-16 maximum   [1;37mTorpedo launchers: [1;32m2
[1;37mMissile launchers: [1;32m2   [1;37mDecoy launcher: [1;32mYes   [1;37mJammer launcher: [1;32mYes
[1;37mZipper launcher: [1;32mYes   [1;37mMine launcher: [1;32mYes
[1;37mAcceleration rate: [1;32m6,000 Su/T   [1;37mTop rated speed: [1;32mWarp 35
[1;37mScanner range: [1;32m250,000 subsectors (25 sectors)   [1;37mCargo capacity: [1;32m40,000 Tons

[1;37mBattle loadout:

Mark-1 shield, Mark-1 phaser, 3 flux pods

Eligible upgrades:

Enhanced scanners, armor plating, acceleration boosters,
reinforced neutron core

} (S05TYPE=USER) T   Help screen for class 05

SXXEND {} T Place holder - do not remove

